### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by ChakshuGautam** [RahatBot/.github#2]
**Goal:** Provide an Admin Panel so that CRUD for FAQs is enabled

**Acceptance Criteria:** 

- Admin should be able to add new FAQ (chunk) - rename chunks to FAQ
- Admin should be able to delete FAQ (chunk) - rename chunks to FAQ
- One excel upload is complete, success message comes up with count of questions created/deleted (chunks)

**Telemetry Information:** None specific

**Test Cases:** 

- Create new FAQ and they should show up in the front end
- Delete FAQ and they should be deleted in the front end

**Requirements:**

- Admin logs in using email ID and password
- Admin has option to create, delete FAQ using an excel upload. Columns in excel are "Disaster", "Question", "Answer", "Create/Delete/Update"
- Pane on top for Admin Panel remains the same as below
- Option to download template which downloads an excel with the format which it needs for upload
- Once an excel is uploaded, it should show a success message with the number of questions created/deleted

**User Flow**:

- Step 1: Login into the web admin portal
- Step 2: Upload an excel to using "Disaster", "Question", "Answer", "Create/Delete" columns

**User Persona:**

- Rahat PMU: Access to Admin Panel and CRUD FAQ

Design:

Should have the same pane in Image 1 and Image 2

![Image](https://github.com/RahatBot/.github/assets/145356240/18e3c3bb-9434-4764-81a6-bb1374198d24)

**Image 1:** ![Image](https://github.com/RahatBot/.github/assets/145356240/26559331-e9a4-49e3-9382-f6cfac4a709d)

**Image 2:** ![Image](https://github.com/RahatBot/.github/assets/145356240/b8ed7d80-94bd-4f2f-903c-2b9920a85fab)

**Comment by rohitsamagra** [comment]
Figma and user flows are missing

**Comment by rohitsamagra** [comment]
Check BhaSAI and see what all is required - check with Ranju whatr is being changed

**Comment by rohitsamagra** [comment]
- Addition of new questions will be possible

**Comment by prtkjakhar** [comment]
https://github.com/BharatSahAIyak/issues/issues/118

**Comment by PriyanshiSoni11** [comment]
https://github.com/BharatSahAIyak/issues/issues/118
QA Task link

**Comment by prtkjakhar** [comment]
Closing this since Rahat Bot is already deployed
